### ISSUE TITLE
2-2부분 질문입니다

### ISSUE THREAD

**Issue by goldentrash** [YWHyuk/2019_SecurityFact_BaekJoon#2]
<code>P(P,K-(S-(Sp1+Sp2+...+Spp)) </code>
공식을 조금만 더 상세하게 설명해 주세요

**Comment by YWHyuk** [comment]
Spx는 고른 주사위가 나온 눈의 값을 의미해요
S-(Sp1+Sp2+Sp3+...+Spp) 는 다르게 표현하면 고르지 않은 주사위들의 눈의 합이에요

**Comment by goldentrash** [comment]
답변 감사합니다!

p(X, Y)함수를 구현하지 못하고 있습니다.
재귀적 방법(p(X, Y) = p(X-1, Y-1) + p(X-1, Y-2) + ---- p(X-1, Y-6))은 너무 비효율적으로 느껴져서 다른 방법을 찾고 있는데, 어떤 방법을 사용하셨나요?

**Comment by YWHyuk** [comment]
다이나믹 프로그래밍을 참고하시면 될 것 같아요

**Comment by YWHyuk** [comment]
space complexity, time complexity를 비교해보면
재귀 space complexity: O(1), time complexity: O(2^n)
dp    space complexity: O(n), time complexity: O(n)
항상 상황에 맞는 것을 골라야겠지요. 메모리가 극한으로 적은 경우에는 눈물을 머금고, 재귀를 해야겠지만 그게 아니라면 dp를 선택하는게 합리적으로 보이네요
